# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Probability mass function of discrete power law greater than or equal to u
#'
#' @param x data vector of positive integers
#' @param u scalar, non-negative integer threshold
#' @param alpha scalar, a numeric value greater than 1.0
#' @return A numeric vector of the same length as x
#' @export
dupp <- function(x, u, alpha) {
    .Call(`_crandep_dupp`, x, u, alpha)
}

#' Survival function of discrete power law greater than or equal to u
#'
#' @param x data vector of positive integers
#' @param u scalar, non-negative integer threshold
#' @param alpha scalar, a numeric value greater than 1.0
#' @return A numeric vector of the same length as x
#' @export
Supp <- function(x, u, alpha) {
    .Call(`_crandep_Supp`, x, u, alpha)
}

mcmc_upp <- function(x, u, xi1, a_xi1, b_xi1, N = 20000L, thin = 10L, burnin = 20000L, print_freq = 10000L) {
    .Call(`_crandep_mcmc_upp`, x, u, xi1, a_xi1, b_xi1, N, thin, burnin, print_freq)
}

dmix <- function(x, xi1, xi2, sig, u, phi, geo, give_log = FALSE) {
    .Call(`_crandep_dmix`, x, xi1, xi2, sig, u, phi, geo, give_log)
}

Smix <- function(x, xi1, xi2, sig, u, phi, geo) {
    .Call(`_crandep_Smix`, x, xi1, xi2, sig, u, phi, geo)
}

mcmc_mix <- function(x, u, xi1, xi2, sig, cont, geo, a_phi, b_phi, a_xi1, b_xi1, m_xi2, s_xi2, a_sig, b_sig, pcont, N = 20000L, thin = 100L, burnin = 20000L, print_freq = 10000L) {
    .Call(`_crandep_mcmc_mix`, x, u, xi1, xi2, sig, cont, geo, a_phi, b_phi, a_xi1, b_xi1, m_xi2, s_xi2, a_sig, b_sig, pcont, N, thin, burnin, print_freq)
}

